name: Python Flask App

on:
  push:
    branches:
      master

  pull__request:
    branches:
      master

jobs:
  build:
    runs-on: ubuntu:latest
    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: install dependencies
      run: |
        pythongit add *.exe -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: run test
      run: |
        pytest