name: Python Flask App

on:
  push:
    branches:
      main

  pull_request:
    branches:
      main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: install dependencies
      run: |
        python3 -m pip3 install --upgrade pip3
        pip3 install -r requirements.txt

    - name: run test
      run: |
        pytest